# Generated by Django 2.2 on 2019-12-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeks_auth', '0002_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
