# Generated by Django 2.2 on 2019-12-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeks_auth', '0003_remove_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
    ]
